firstproject/firstapp/urls.py
from django.urls import path 
from . import views 

app_name = 'firstapp' 

urlpatterns = [ 
	path('', views.index, name='index'),
	path('<int:question_id>/', views.question, name='question'),
]

firstproject/firstproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('firstapp/', include('firstapp.urls')),
    path('picsl/', include('picsl.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT)

firstproject/picsl/urls.py
from django.urls import path 
from . import views 

app_name = 'picsl' 

urlpatterns = [ 
	path('', views.index, name='index'),
	# path('<int:question_id>/', views.question, name='question'),
	path('upload/', views.upload, name='upload'),
]

firstproject/firstapp/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
	text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('data published')

firstproject/picsl/models.py
from django.db import models
import exif
from datetime import datetime

# Create your models here.

class Images(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=280)
    image = models.ImageField(upload_to = '%Y/')
    date_loaded = models.DateTimeField(auto_now_add=True)
    datetime_original = models.DateTimeField(null=True)

    def save(self, *args, **kwargs):
        """Override save to get exif data before saving"""

        imageExif = exif.Image(self.image)
        if (imageExif.datetime_original):
            do = imageExif.datetime_original
            self.datetime_original = datetime.strptime(do, '%Y:%m:%d %H:%M:%S')

        super(Images, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

firstproject/picsl/forms.py
from django import forms
from .models import Image

class ImageForm(forms.ModelForm):
    # your_name = forms.CharField(label='Your name', max_length=100)
    class Meta:
        model = Image
        fields = ("title", "image")

firstproject/firstapp/views.py
from .models import Question
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'picsl/index.html', context)

def upload(request):
    return render(request, 'picsl/upload.html')

firstproject/picsl/views.py
# from .models import Question
from django.shortcuts import render
# from django.http import HttpResponse, HttpResponseRedirect
from .models import Images
# from django.urls import reverse

def index(request):
    """ display front page """
    all_images = Images.objects.all()
    context = {"images": all_images}
    return render(request, "picsl/index.html", context)


def upload(request):
    """Upload image form"""
    if (request.method) == "POST":
        image = Images(
            title = request.POST['title'],
            image = request.FILES['image'],
            description = request.POST['description'],
        )
        image.save()
        return render(request, "picsl/upload.html", {
            "image_loaded": True,
            "image_title": request.POST['title'],
            "image_description": request.POST['description'],
        })
    else:
        return render(request, "picsl/upload.html")

firstproject/firstapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PICSL</title>
    <link rel="apple-touch-icon" href="icon.png">
    <link rel="stylesheet" href="{% static 'firstapp/bulma.min.css' %}">
    <meta name="theme-color" content="#fafafa">
</head>

<body>
    <nav class="navbar" role="navigation" aria-label="main navigation">

        <div class="navbar-brand">
            <div class="navbar-item">
                <img src="{% static 'firstapp/picsl-brand.svg' %}" height="28" width="112">
            </div>
            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div class="navbar-menu">
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-light">
                            Log in
                        </a>
                    </div>
                </div>
            </div>
        </div>

    </nav>

    <section class="section">
        <div class="columns">
            <main class="column is-two-thirds">
                {% block content %}{% endblock %}
            </main>
            <div class="column" id="sidebar">
                <nav class="panel">
                    <p class="panel-heading">
                        Sidebar
                    </p>
                    <div class="panel-block">
                        <p class="control has-icons-left">
                            <input class="input" type="text" placeholder="Search">
                            <span class="icon is-left">
                                <i class="fas fa-search" aria-hidden="true"></i>
                            </span>
                        </p>
                    </div>
                    <div class="panel-block is-active">
                        
                        <span class="panel-icon">
                            <ion-icon name="image-outline" style="color:maroon"></ion-icon>
                        </span>

                        picsl : a personal photo-sharing website
                        
                    </div>
                </nav>
            </div>

        </div>
    </section>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

</html>

firstproject/firstapp/templates/firstapp/index.html
{% extends "base.html" %}

{% block pagetitle %}Index{% endblock %}

{% block content %}
{% if latest_question_list %}
<ul>
	{% for question in latest_question_list %}
        <li>
            <a href="/firstapp/{{ question.id }}/">{{ question.text }}</a>
            <small>{{ question.pub_date }}</small>
        </li>
    {% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}
{% endblock %}

firstproject/firstapp/templates/firstapp/question.html
{% extends "base.html" %}

{% block pagetitle %}Question{% endblock %}

{% block content %}
<h2 class="title is-2">Question Page</h2>
<p>You are looking at the page for question {{ question.id }}</p>
<p><q>{{ question.text }}</q></p>
<p>Published: {{ question.pub_date }}</p>
{% endblock %}

firstproject/picsl/templates/picsl/index.html
{% extends "picsl_base.html" %}

{% block content %}

<main class="container">
    <div class="wrap-container">
        {% for image in images %}
        <div class="box">
            <div><img src="{{ image.image.url }}" style="max-width: 100%"></div>
            <div class="columns">
                <div class="column">
                    
                    <h2 class="title is-6">{{image.title}}</h2>
                    <div>{{image.description}}</div>
                </div>
                <div class="column has-text-right">
                    <div>Taken: <i class="is-italic">{{image.datetime_original}}</i></div>
                    <div>Uploaded: <i class="is-italic">{{image.date_loaded}}</i></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>

{% endblock %}

firstproject/picsl/templates/picsl/upload.html
{% extends "picsl_base.html" %}
{% load static %}


{% block content %}

{% if image_loaded %}
<p>Image loaded successfully:</p>
<p>Title: {{image_title}}</p>
<p>Description: {{image_description}}</p>
{% endif %}

<form action="{% url 'picsl:upload' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="field">
        <label class="label" for="image">Select Image</label>
        <div class="control">
            <input class="input" id="image-select" accept="image/*" name="image" required="" type="file">
        </div>
        <div id="image-preview"></div>
    </div>
    <div class="field">
        <label class="label" for="title">Title</label>
        <div class="control">
            <input class="input" id="title-input" type="text" name="title" size="50" maxlength="50" minlength="1" />
        </div>
    </div>
    <div class="field">
        <label class="label" for="description">Description</label>
        <div class="control">
            <input class="input" type="text" name="description" maxlength="280" />
        </div>
    </div>
    <div class="control">
        <button class="button" type="submit">Upload</button>
    </div>
</form>

<script src="{% static 'picsl/upload.js' %}"></script>

{% endblock %}

firstproject/picsl/templates/picsl_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PICSL</title>
    <link rel="apple-touch-icon" href="icon.png">
    <link rel="stylesheet" href="{% static 'picsl/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'picsl/style.css' %}">
    <meta name="theme-color" content="#fafafa">

</head>

<body>
    <nav class="nav-flex" role="navigation" aria-label="main navigation">
        <div class="item">
            <a href="{% url 'picsl:index' %}">
                <img src="{% static 'picsl/picsl-brand.svg' %}" height="28" width="112">
            </a>
        </div>

        <div class="item">
            <nav class="block">
                <a class="button is-primary" href="upload">Upload Pic</a>
            </nav>
        </div>
    </nav>


    <section class="section">
        {% block content %}{% endblock %}
    </section>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>

</html>